service: api-js-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: us-east-1
  stage: qa
  versionFunctions: false
  httpApi:
    cors: true
    name: ${self:service}-${self:provider.stage}-api
  environment:
    ENV_PREFIX: ${self:service}-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - s3:*
            - dynamodb:*
            - ssm:*
            - sqs:*
            - scheduler:*
            - iam:*
          Resource: "*"
package:
  individually: true
  patterns: ["!**/*", "package.json"]
custom:
  version: "v1"
  prefix: ${self:service}-${self:provider.stage}
functions:
  initial:
    handler: dist/index.js.handler
    events:
      - httpApi:
          method: Get:
          path: /${self:custom.version}/health

